version: '3.8'
services:
  wordpress:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./logs/access:/var/log/access
      - ./logs/error:/var/log/error
    depends_on:
      - db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: example

