version: '3.9'
services:
  nignx: 
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html:delegated
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: sercet
      MYSQL_ROOT_PASSWORD: secret
  php:
    image: php:7.4-fpm-alpine
    volumes:
      - ./wordpress:/var/www/html:delegated
    